# Generated by Django 5.1 on 2024-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionals',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='useradditionals',
            name='password_for_comet_deleting',
            field=models.BooleanField(default=True),
        ),
    ]
