# Generated by Django 5.1 on 2024-09-11 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PlanetMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Owner'), (3, 'Banned')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
