# Generated by Django 5.1 on 2024-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_planet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
