# Generated by Django 5.1 on 2024-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
