# Generated by Django 5.1 on 2024-10-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetmemberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetmembership',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Owner')], default=0),
        ),
    ]
